/*1355718384,173213215*/

if (self.CavalryLogger) { CavalryLogger.start_js(["KHWKY"]); }

function MetaComposerMessageBox(){}copyProperties(MetaComposerMessageBox.prototype,{init:function(a,b){this.inputContainer=DOM.scry(a,'div.inputContainer')[0];this.textInput=DOM.scry(a,'textarea.mentionsTextarea')[0];this.metaArea=DOM.scry(a,'div.attachmentMetaArea')[0];this.bottomArea=DOM.scry(a,'div.attachmentBottomArea')[0];this.barArea=DOM.scry(a,'div.attachmentBarArea')[0];Event.listen(this.inputContainer,'click',function(c){var d=c.getTarget();if(!DOM.contains(this.metaArea,d)&&d!==this.textInput)this.textInput.focus();}.bind(this));}});
__d("ScrollableTypeaheadBehavior",["DOM","CSS","Style","Parent","cx","ScrollableArea","copyProperties"],function(a,b,c,d,e,f){var g=b('DOM'),h=b('CSS'),i=b('Style'),j=b('Parent'),k=b('cx'),l=b('ScrollableArea'),m=b('copyProperties');function n(o){this._typeahead=o;}m(n.prototype,{_subscriptions:null,_scrollableElems:null,_scrollableArea:null,_showScrollbar:null,enable:function(){this._scrollableElems=(l.renderDOM());h.addClass(this._scrollableElems.root,"_ml");g.appendContent(this._typeahead.getView().element,this._scrollableElems.root);this._typeahead.getView().content=this._scrollableElems.content;this._scrollableArea=(l.fromNative(this._scrollableElems.root,{fade:false}));this._subscriptions=[this._typeahead.getView().subscribe('reset',this._reset.bind(this)),this._typeahead.getView().subscribe('render',this._render.bind(this)),this._typeahead.getView().subscribe('beforeRender',this._beforeRender.bind(this)),this._typeahead.getView().subscribe('next',this._scrollHelper.bind(this)),this._typeahead.getView().subscribe('prev',this._scrollHelper.bind(this))];i.set(this._scrollableElems.wrap,'height','0px');h.removeClass(this._scrollableElems.root,"_mm");},disable:function(){while(this._subscriptions.length)this._subscriptions.pop().unsubscribe();this._subscriptions=null;},_reset:function(){i.set(this._scrollableElems.wrap,'height','0px');h.removeClass(this._scrollableElems.root,"_mm");this._scrollableArea.scrollToTop();},_render:function(){this._scrollableArea.poke();this._showScrollbar?this._scrollableArea.showScrollbar(false):this._scrollableArea.hideScrollbar(true);h.addClass(this._scrollableElems.root,"_mm");},_beforeRender:function(o,p){var q=5;if(this._typeahead.getView().maxResults<10)q=3;i.set(this._scrollableElems.body,'width',this._scrollableElems.wrap.offsetWidth+'px');if(p.results.length<q){i.set(this._scrollableElems.wrap,'height',(38*p.results.length+4)+'px');this._showScrollbar=false;}else{this._scrollableArea.showScrollbar(false);i.set(this._scrollableElems.wrap,'height',(38*q+4)+'px');this._showScrollbar=true;}},_scrollHelper:function(o,p){if(!j.byClass(p,'uiScrollableArea'))return;this._typeahead.getView().ignoreMouseover=true;var q=j.byClass(p,'uiScrollableAreaWrap'),r=p.offsetTop-q.offsetTop;if(r<q.scrollTop){q.scrollTop=r;return;}var s=r+p.offsetHeight;if(s>q.scrollTop+q.offsetHeight)q.scrollTop=s-q.offsetHeight;}});e.exports=n;});
__d("legacy:LegacyScrollableTypeaheadBehavior",["ScrollableTypeaheadBehavior"],function(a,b,c,d){var e=b('ScrollableTypeaheadBehavior');if(!a.TypeaheadBehaviors)a.TypeaheadBehaviors={};a.TypeaheadBehaviors.scrollArea=function(f){f.enableBehavior(e);};},3);
var TimelineAggregatePost={init:function(a){Event.listen(a,'click',function(b){var c=b.getTarget();if(b.isDefaultRequested()||c.tagName==='A'||Parent.byClass(c,"_1ww"))return true;var d=Parent.byTag(c,'li'),e=DataStore.get(d,'url');AsyncRequest.bootstrap(e,d);});},initPage:function(a){Event.listen(a,'click',function(b){var c=Parent.byClass(b.getTarget(),'uiCloseButton');if(c)return;var d=Parent.byTag(b.getTarget(),'li');new AsyncRequest().setURI(DataStore.get(d,'url')).send();});},poke:function(a){ScrollableArea.poke(a);},setScrollHeight:function(a){var b=DOM.find(a,'.sArea');Style.set(b,'height',a.offsetHeight+'px');}};
__d("TimelinePageMostRecent",["CSS","DOMQuery","Parent","Style","TimelineCapsule","$"],function(a,b,c,d,e,f){var g=b('CSS'),h=b('DOMQuery'),i=b('Parent'),j=b('Style'),k=b('TimelineCapsule'),l=b('$'),m={init:function(n,o){if(!g.shown(n)){g.show(n);var p=l(o);j.set(h.find(p,'div.sArea'),'height',(p.offsetHeight||0)+'px');k.balanceCapsule(i.byClass(l(n),'fbTimelineCapsule'));}}};e.exports=m;});
__d("TimelineCommentsLoader",["event-extensions","CommentPrelude","CSS","DOM","Parent","emptyFunction"],function(a,b,c,d,e,f){b('event-extensions');var g=b('CommentPrelude'),h=b('CSS'),i=b('DOM'),j=b('Parent'),k=b('emptyFunction'),l={init:function(){l.init=k;Event.listen(document.body,'click',function(m){var n=j.byClass(m.getTarget(),'fbTimelineFeedbackCommentLoader');if(n){m.kill();g.click(n,false);var o=j.byTag(n,'form'),p=i.scry(o,'li.uiUfiViewAll input');if(!p.length)p=i.scry(o,'li.fbUfiViewPrevious input');if(!p.length)p=i.scry(o,'a.UFIPagerLink');p[0].click();h.show(i.find(o,'li.uiUfiComments'));h.removeClass(n,'fbTimelineFeedbackCommentLoader');}});}};e.exports=l;});